# Ruby-wordchain
# Read in word graph generated by genwordgraph.rb
# A LOT faster than before.

$nodes = File.open("word_graph.txt", "rb") {|f| Marshal.load(f)} 

def find_path(start, endword, maxdepth=5)
  return [false, nil] if maxdepth == 0
  return [false, nil] if !$nodes[start]
  return [false, nil] if !$nodes[endword]
  if $nodes[start].include?(endword)
    return [true,[start, endword]]
  else
    $nodes[start].each do |y|
      result = find_path(y, endword, maxdepth-1)  
      if result.first
        return [true, result[1].unshift(start)]
      end 
    end
    return [false, nil]
  end
end

puts find_path("HATE", "LOVE")
